# Generated by Django 4.0.3 on 2022-03-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=80)),
                ('assinaturaFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watching.assinatura')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('ano_lancamento', models.CharField(max_length=5)),
                ('categoriaFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watching.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmeFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watching.filme')),
                ('usuarioFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watching.usuarios')),
            ],
        ),
    ]
